"""Interactive .env writer — `python -m prodagent.playground.config_init`."""

from __future__ import annotations

import sys
from pathlib import Path


def _prompt(msg: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"{msg}{suffix}: ").strip()
    return val or (default or "")


def _select_path() -> dict[str, str]:
    print("\nChoose LLM path:")
    print("  1) FakeLLM — offline, no key (for trying the playground)")
    print("  2) OpenAI-compatible — any vendor with an OpenAI-style /v1 endpoint")
    print("     (DeepSeek, Qwen, Moonshot, Zhipu, Groq, Ollama, self-hosted, ...)")
    while True:
        choice = input("\nEnter number: ").strip()
        if choice == "1":
            return {"USE_FAKE_LLM": "1"}
        if choice == "2":
            return _collect_openai_compat()
        print(f"  Invalid choice: {choice!r}, try again.")


def _collect_openai_compat() -> dict[str, str]:
    print("\n  OpenAI-compatible endpoint:")
    base_url = _prompt("  LLM_BASE_URL (e.g. https://open.bigmodel.cn/api/paas/v4)")
    api_key = _prompt(
        "  LLM_API_KEY (从厂商控制台创建,如智谱 https://open.bigmodel.cn/usercenter/apikeys)"
    )
    model = _prompt("  LLM_MODEL (e.g. glm-5.2)")
    env = {"LLM_BASE_URL": base_url, "LLM_API_KEY": api_key, "LLM_MODEL": model}
    if not api_key:
        print("    [warn] LLM_API_KEY empty — many vendors will reject calls.")
    if not model:
        print("    [warn] LLM_MODEL empty — will default to gpt-4o.")
    return env


def _write_env(env: dict[str, str], path: Path) -> None:
    if path.exists():
        overwrite = input(f"\n{path} exists, overwrite? [y/N] ").strip().lower()
        if overwrite != "y":
            print("Cancelled.")
            return
    lines = ["# prodagent playground LLM config — generated by `make config`."]
    for k, v in env.items():
        if v:
            lines.append(f"{k}={v}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n[ok] wrote {path}")
    print("  `make playground` will pick it up automatically.")


def main() -> int:
    print("=" * 60)
    print("  prodagent playground — LLM config")
    print("=" * 60)
    env = _select_path()
    _write_env(env, Path.cwd() / ".env")
    return 0


if __name__ == "__main__":
    sys.exit(main())
